apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
    - name: front-container
      image: gcr.io/<PROJECT_ID>/front-container:latest
      ports:
      - containerPort: 8080
    - name: sidecar-container
      image: gcr.io/<PROJECT_ID>/sidecar-container:latest
      ports:
      - containerPort: 8081